export * from "@/pages/home";
export * from "@/pages/profile";
export * from "@/pages/sign-in";
export * from "@/pages/sign-up";
export * from "@/pages/convocatorias";
export * from "@/pages/convocatoriaindividual";
export * from "@/pages/talleresydiplomados";
export * from "@/pages/taller";
export * from "@/pages/tallerindividual";
export * from "@/pages/postulacion";
export * from "@/pages/postulacionConvocatoria";
export * from "@/pages/programas";
export * from "@/pages/PostulacionesPendientesPage";
export { default as Requisitar_Taller } from "./Requisitar_Taller";
export { default as RondaUnoEvaluacion } from "./RondaUnoEvaluacion";
export { default as PostulacionesEvaluar } from "./PostulacionesEvaluar";
export { default as RondaFinal } from "./RondaFinal";
export * from "@/pages/convocatorias";
//export * from "@/pages/PerfilGanador";
export { default as PerfilGanador } from "./PerfilGanador";
export { default as RegistroPostal } from "./RegistroPostal";
